### PR TITLE
simplify header when page is <iframe>'d

### PR DESCRIPTION
**Pull request by cvan**
# `<iframe>`'d

# full page

Let me know your thoughts. Thanks!

### CODE REVIEW

**Comment by ericduran** [comment]
I like the idea. I wanted to have an embed version. Which I was going to completely get rid of the toolbar and the "network" image since it's so large.

**Comment by cvan** [comment]
I'll remove the "network" image and update the PR

**Comment by cvan** [comment]
updated:

**Comment by ericduran** [comment]
@cvan much nicer :+1:

**Pull request merged**
